branch: 
  - name: "master"
  - name: "beta"
    prerelease: true

plugins:
  - name: "@semantic-release/commit-analyzer"
  - name: "@semantic-release/release-notes-generator"
  - name: "@semantic-release/changelog"
    changelogFile: "docs/CHANGELOG.md"
  - name: "@semantic-release/git"
  - name: "@semantic-release/github"